### ISSUE TITLE
[BUG] User configuration dialog is black

### ISSUE THREAD

**Issue by noncasus** [kristianserrano/sticky-folders#1]
Hello!

You seem to be overriding the background color for the user configuration dialog. I've posted an image.

![image](https://github.com/kristianserrano/sticky-folders/assets/6765904/03404cca-673f-457d-ad95-0a89fca8ff8d)

**Comment by kristianserrano** [comment]
Strange that Foundry is using the `directory` class there! I'll try to release a fix ASAP though.

**Comment by kristianserrano** [comment]
Fixed in v1.0.2!
